language: node_js
sudo: false
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_78a9425f57b4_key -iv $encrypted_78a9425f57b4_iv
    -in guson.enc -out ~/.ssh/guson -d
  - chmod 600 ~/.ssh/guson
  - echo -e "Host damon.xcworld.cn\n\tUser $gusername\n\tHostname damon.xcworld.cn\n\tIdentityFile ~/.ssh/guson\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cat ~/.ssh/config
  - npm install pm2 -g
after_success:
  - pm2 deploy ecosystem.config.js dev
