language: node_js
sudo: false
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_78a9425f57b4_key -iv $encrypted_78a9425f57b4_iv
    -in ./scripts/server.enc -out ~/.ssh/guson -d
  - chmod 600 ~/.ssh/guson
after_success:
  - npm prune --production
  - pm2 deploy ecosystem.config.js dev
